# Generated by Django 3.1.13 on 2021-09-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210907_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_password_update_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last password update time'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_reset_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='password reset time'),
        ),
    ]
