# Generated by Django 3.1.13 on 2021-11-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='department'),
        ),
    ]
