# Generated by Django 3.1.13 on 2021-09-07 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RitFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('frequency', models.IntegerField(choices=[(1, 'Daily'), (2, 'Weekly'), (3, 'Monthly'), (4, 'Quarterly'), (5, 'Semi Annual'), (6, 'Yearly')], default=1)),
                ('version', models.FloatField(blank=True, verbose_name='version')),
                ('column', models.IntegerField(verbose_name='column(s)')),
                ('row', models.IntegerField(verbose_name='row(s)')),
                ('cut_off_days', models.IntegerField(verbose_name='cut off day(s)')),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=0)),
                ('validate', models.BooleanField(default=False, verbose_name='validate')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutes.department')),
            ],
        ),
        migrations.CreateModel(
            name='RitSupervision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_date', models.DateTimeField(verbose_name='base date')),
                ('file', models.CharField(max_length=255, verbose_name='file')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='phone')),
                ('prepared_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='prepared by')),
                ('upload_time', models.DateTimeField(verbose_name='upload time')),
                ('status', models.IntegerField(choices=[(1, 'Uploaded'), (2, 'Failed to upload for error at first row')], default=1)),
                ('ip', models.CharField(blank=True, max_length=255, verbose_name='ip address')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutes.branch')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutes.department')),
                ('financial_institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutes.financialinstitute')),
                ('financial_institute_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutes.financialinstitutetype')),
                ('rit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rit.ritfeatures')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_uploaded_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RitManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_date', models.DateTimeField(verbose_name='base date')),
                ('file', models.CharField(max_length=255, verbose_name='file')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutes.branch')),
                ('financial_institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutes.financialinstitute')),
                ('rit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rit.ritfeatures')),
            ],
        ),
    ]
