# Generated by Django 3.1.13 on 2021-09-21 11:25

from django.db import migrations, models
import ereturns.common.file_upload


class Migration(migrations.Migration):

    dependencies = [
        ('rit', '0002_auto_20210912_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ritmanagement',
            name='file',
            field=models.FileField(upload_to=ereturns.common.file_upload.rit_directory_path),
        ),
        migrations.AlterField(
            model_name='ritmanagement',
            name='file_type',
            field=models.IntegerField(choices=[(1, 'RIT'), (2, 'Reference File'), (3, 'User Manual'), (4, 'User Registration Form')], default=1),
        ),
        migrations.AlterField(
            model_name='ritsupervision',
            name='file',
            field=models.FileField(upload_to=ereturns.common.file_upload.directory_path),
        ),
    ]
