# Generated by Django 3.1.13 on 2021-10-11 09:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rit', '0003_auto_20210921_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ritsupervision',
            name='upload_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='upload time'),
        ),
    ]
